// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT users (id, created_at, updated_at, name)
`

func (q *Queries) GetUser(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var users interface{}
	err := row.Scan(&users)
	return users, err
}
